# frozen_string_literal: true

require "json"
require "openssl"
require "securerandom"
require "time"
require "uri"

require_relative "shopee_rb_api/version"
require_relative "shopee_rb_api/endpoints"
require_relative "shopee_rb_api/errors"
require_relative "shopee_rb_api/error_table"
require_relative "shopee_rb_api/redaction"
require_relative "shopee_rb_api/values"
require_relative "shopee_rb_api/response"
require_relative "shopee_rb_api/pager"
require_relative "shopee_rb_api/retry_policy"
require_relative "shopee_rb_api/signer"
require_relative "shopee_rb_api/multipart"
require_relative "shopee_rb_api/transport/net_http"
require_relative "shopee_rb_api/connection"
require_relative "shopee_rb_api/webhook"
require_relative "shopee_rb_api/resources/base"
require_relative "shopee_rb_api/resources/categories"
require_relative "shopee_rb_api/resources/brands"
require_relative "shopee_rb_api/resources/media"
require_relative "shopee_rb_api/resources/products"
require_relative "shopee_rb_api/resources/stock"
require_relative "shopee_rb_api/resources/prices"
require_relative "shopee_rb_api/resources/orders"
require_relative "shopee_rb_api/resources/variants"
require_relative "shopee_rb_api/resources/attributes"
require_relative "shopee_rb_api/auth"
require_relative "shopee_rb_api/shop"
require_relative "shopee_rb_api/client"
require_relative "shopee_rb_api/extensions"
